### ISSUE TITLE
Add setting to add emoticon to description

### ISSUE THREAD

**Issue by mojo2012** [1tchy/mooncal#1]
Hi guys, awesome calendar! :-) But how cool would it be to use the emoticons in the description? 🌘🌓🌔🌑
It should be optional though I guess

**Comment by 1tchy** [comment]
Thanks for the kudos and great idea! But I think making it optional would clutter the GUI.

**Comment by 1tchy** [comment]
I've added them with commit https://github.com/1tchy/mooncal/commit/338fe85c15ad4b72490b450008e931900e2b5db6 😃

**Comment by mojo2012** [comment]
Just awesome! :-)
