### ISSUE TITLE
Help Remove

### ISSUE THREAD

**Issue by JKam403** [1tchy/mooncal#11]
How do I remove over 2 years of daily calendar moon phases that are blocking my whole calendar? I can only remove them day by day. There must be another way. It’s a nightmare and wish I’d never put this code in.

**Comment by 1tchy** [comment]
If you have added Mooncal as a calendar subscription, you can just unsubscribe. If you downloaded the file and added it to an existing calendar, this depends on your calendar application. You may consult with them. I unfortunately cannot help you with this.
Thanks however for your feedback! I consider to add a warning to Mooncal, when future users download lots of calendar entries.

**Comment by JKam403** [comment]
Wow, what a nightmare. Did as you all directed and now I have over 2 years so over 365 x 2 daily calendar entries to delete individually. This is your doing and can’t believe this wasn’t either made clear or set up properly. Furious. Jacyntha Kamorjacynthakamor.comOn Sep 2, 2024, at 01:07, Itchy ***@***.***> wrote:﻿
If you have added Mooncal as a calendar subscription, you can just unsubscribe. If you downloaded the file and added it to an existing calendar, this depends on your calendar application. You may consult with them. I unfortunately cannot help you with this.
Thanks however for your feedback! I consider to add a warning to Mooncal, when future users download lots of calendar entries.
